# Generated by Django 3.2.3 on 2021-05-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_allergy_allergy_product'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allergy_product',
            table='allergy_products',
        ),
    ]
